### ISSUE TITLE
README

### ISSUE THREAD

**Issue by hroncok** [fedora-python/fedoralovespython.org#18]
This repo lacks a README. It should include:
- what's here
- how is it deployed
- what's the license
- who made it and why

**Comment by encukou** [comment]
Also mention Flask server deployment, e.g. `FLASK_APP=fedoralovespython.py python3 -m flask run`

**Comment by hroncok** [comment]
This is getting serious :)

**Comment by nmilosev** [comment]
Also instructions for running on Termux:

```
dnf install -y git python3-flask python3-markdown python3-yaml

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

git clone https://github.com/fedora-python/fedoralovespython.org
cd fedoralovespython.org

FLASK_APP=fedoralovespython.py python3 -m flask run
```

I could write a bash script to run it if you want. :) It would even have to be in this repo.

**Comment by hroncok** [comment]
@nmilosev I don't think running in Termux is so serious to put a bash script. The Flask based run will be documented.

**Comment by nmilosev** [comment]
@hroncok You're probably right, but it is a very cool showcase for conferences. :) Maybe put it somewhere, I can write about it on my blog. :)
