### ISSUE TITLE
Finish the styling & pictures

### ISSUE THREAD

**Issue by encukou** [fedora-python/fedoralovespython.org#3]
Left over from #2:
- [x] Sticker-style logos for all the points
- [x] Point out sticker licensing
- [ ] Embed the font?

**Comment by hroncok** [comment]
What about this:

> This site is not affiliated with either the Fedora Project or the Python Software Foundation. The content, except for any trademarked logos, or unless otherwise noted is licensed under [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/legalcode) (by members of [Fedora Python SIG](https://fedoraproject.org/wiki/SIGs/Python)). The MicroBit picture is _Copyright &copy; 2016 British Broadcasting Corporation_, licensed under [MIT](https://github.com/lancaster-university/microbit-docs/blob/master/LICENSE). All product names, logos, and brands are property of their respective owners.

**Comment by hroncok** [comment]
Logos in #4, copyright in #5.

**Comment by hroncok** [comment]
What is the advantage of embedding the font?

**Comment by encukou** [comment]
I guess there isn't any, now.

**Comment by hroncok** [comment]
> What is the advantage of embedding the font?

Doing `serve` on a train ;)

**Comment by encukou** [comment]
Ah, right. I did something like:

```
git clone https://github.com/google/fonts google-fonts
ln -s $PWD/google-fonts ~/.fonts/google-fonts
```
