### ISSUE TITLE
Possibly confusing license

### ISSUE THREAD

**Issue by hroncok** [fedora-python/fedoralovespython.org#34]
There is no general LICENSE file, only LICENSE.code (MIT) and LICENSE.content (CC). However, the README says nothing about the code being MIT.

**Comment by Sanqui** [comment]
In addition, GitHub interprets the two licenses strangely.

The license of the whole repository is noted as MIT on the homepage.
[LICENSE.code](https://github.com/fedora-python/fedoralovespython.org/blob/master/LICENSE.code) is MIT and shows no GitHub license header.
However, [LICENSE.content](https://github.com/fedora-python/fedoralovespython.org/blob/master/LICENSE.content) is CC BY 4.0, yet it shows a GitHub license header for MIT!

This seems like a GitHub bug.

**Comment by hroncok** [comment]
It seems.
