### ISSUE TITLE
Update the "Python 3 by default" phrasing?

### ISSUE THREAD

**Issue by brainwane** [fedora-python/fedoralovespython.org#43]
Right now the "Python 3 by default" section (per #11) includes:

> When you install Fedora Workstation or Cloud, there's no Legacy Python installed by default. However, `/usr/bin/python` remains Python 2, as described in [PEP 394](https://www.python.org/dev/peps/pep-0394/).

But perhaps this could have a brief sentence saying that [in the future `/usr/bin/python` will mean Python 3](https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3)?

**Comment by hroncok** [comment]
Good suggestion. Let's wait for the approval of https://fedoraproject.org/wiki/Changes/Python_means_Python3 and do that if it gets it.
