### ISSUE TITLE
Hide "Science stuff"

### ISSUE THREAD

**Issue by encukou** [fedora-python/fedoralovespython.org#49]
Nowadays, you can install Scipy everywhere using wheels. Fedora isn't much of an advantage here.
If we add more points, we should consider hiding Science stuff so the page isn't overwhelming.

**Comment by hroncok** [comment]
Our numpy, scipy etc. now uses FlexiBLAS: https://fedoraproject.org/wiki/Changes/FlexiBLAS_as_BLAS/LAPACK_manager

Not sure if this is something to justify keeping the science point, but maybe?

**Comment by hroncok** [comment]
I've created https://github.com/fedora-python/fedoralovespython.org/pull/55 partially to have a valid reason to keep the point. Close this?
