### ISSUE TITLE
The site background vs. sticker background difference is too low

### ISSUE THREAD

**Issue by hroncok** [fedora-python/fedoralovespython.org#8]
Until today, I always looked at the website from my home, currently looking at it form our 3D lab on the same model of display, but in different lightning conditions and I can barely see the border between the sticker and the page background. It's hard to show, because a screenshot won't do, but here's an attempt of a pic:

![2016-09-02 17 25 19](https://cloud.githubusercontent.com/assets/2401856/18209249/45fb5b22-7133-11e6-953c-7e154450d808.jpg)

**Comment by encukou** [comment]
I was able to somewhat reproduce with `xrandr --output LVDS1 --gamma 3:3:3`,\* but that makes everything pretty unreadable. I think there should be a perceptible difference between white and `#e4e6e8`.

By the way, the color is the same as on [Fedora Developer Portal](https://developer.fedoraproject.org/tech/languages/python/python-installation.html). Do you also see no difference there, between the backgrounds of "Share your knowledge" and the main page?

I'm inclined to leave this as it is, but I'd be willing to listen to someone with a background in web design.

The screenshot doesn't look _that_ bad... :)

---

\* _use `1:1:1` to get back_

**Comment by hroncok** [comment]
I tweaked my display settings at home and this issue only happens with contrast at 100 %. I'll check my display setting at lab and see if that's the issue.
